// Normalized product categories — users pick from this list
// rather than typing their own, ensuring consistency across both partners.

export const CATEGORIES = [
  'Bakery & Bread',
  'Beans & Legumes',
  'Beverages',
  'Candy & Snacks',
  'Canned & Jarred Goods',
  'Condiments & Sauces',
  'Dairy & Eggs',
  'Deli & Prepared Foods',
  'Dry Goods & Pasta',
  'Frozen Foods',
  'Grains & Rice',
  'Health & Beauty',
  'Household & Cleaning',
  'Meat & Seafood',
  'Nuts, Seeds & Dried Fruit',
  'Oils & Vinegars',
  'Organic',
  'Pet Supplies',
  'Produce — Fruit',
  'Produce — Vegetables',
  'Spices & Baking',
  'Vitamins & Supplements',
  'Other',
]

export const CATEGORY_ICONS = {
  'Bakery & Bread': '🍞',
  'Beans & Legumes': '🫘',
  'Beverages': '🥤',
  'Candy & Snacks': '🍿',
  'Canned & Jarred Goods': '🥫',
  'Condiments & Sauces': '🫙',
  'Dairy & Eggs': '🥛',
  'Deli & Prepared Foods': '🥪',
  'Dry Goods & Pasta': '🍝',
  'Frozen Foods': '🧊',
  'Grains & Rice': '🌾',
  'Health & Beauty': '🧴',
  'Household & Cleaning': '🧹',
  'Meat & Seafood': '🥩',
  'Nuts, Seeds & Dried Fruit': '🥜',
  'Oils & Vinegars': '🫒',
  'Organic': '🌿',
  'Pet Supplies': '🐾',
  'Produce — Fruit': '🍎',
  'Produce — Vegetables': '🥦',
  'Spices & Baking': '🧂',
  'Vitamins & Supplements': '💊',
  'Other': '📦',
}
